package GiaoDien;

import TrungGian.KhuyenMai;
import XuLy.KhuyenMaiXuLy;
import java.awt.Window;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ngotr
 */
public class ThemKhuyenMai extends javax.swing.JPanel {

    private KhuyenMaiXuLy khuyenmaiXuLy = new KhuyenMaiXuLy();
    private DefaultTableModel khuyenMaiTableModel;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    public static KhuyenMai khuyenMaiChon = null;
    
    public ThemKhuyenMai() {
        initComponents();
        khoiTaoBang();
        hienThiDanhSachKhuyenMai();
    }

    private void khoiTaoBang() {
        khuyenMaiTableModel = new DefaultTableModel(
                new Object[][] {},
                new String[] {"Mã KM", "Tên KM", "Mã SP", "Ưu đãi", "Ngày bắt đầu", "Ngày kết thúc", "Tình trạng"}
        );
        jTable1.setModel(khuyenMaiTableModel);
    }

    private void hienThiDanhSachKhuyenMai() {
        khuyenMaiTableModel.setRowCount(0);
        khuyenmaiXuLy.docDanhSach();
        ArrayList<KhuyenMai> danhSachKhuyenMai = khuyenmaiXuLy.getDanhSachKhuyenMai();

        for (KhuyenMai km : danhSachKhuyenMai) {
            String tinhTrang = (km.getNgayBD().before(new Date()) && km.getNgayKT().after(new Date())) 
                             ? "Có hiệu lực" : "Không hiệu lực";
            khuyenMaiTableModel.addRow(new Object[] {
                    km.getMaKM(),
                    km.getTenKM(),
                    km.getMaSP(),
                    km.getUuDai(),
                    (km.getNgayBD() != null) ? sdf.format(km.getNgayBD()) : "",
                    (km.getNgayKT() != null) ? sdf.format(km.getNgayKT()) : "",
                    tinhTrang
            });
        }
    }
    private void xuLyChonKhuyenMai() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một khuyến mãi từ bảng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (jTable1.getValueAt(row, 6).equals("Không hiệu lực")) {
            JOptionPane.showMessageDialog(this, "Mã khuyến mãi này đã hết hiệu lực!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int maKM = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String tenKM = jTable1.getValueAt(row, 1).toString();
            int maSP = Integer.parseInt(jTable1.getValueAt(row, 2).toString());
            int uuDai = Integer.parseInt(jTable1.getValueAt(row, 3).toString());
            Date ngayBD = sdf.parse(jTable1.getValueAt(row, 4).toString());
            Date ngayKT = sdf.parse(jTable1.getValueAt(row, 5).toString());

            khuyenMaiChon = new KhuyenMai();
            khuyenMaiChon.setMaKM(maKM);
            khuyenMaiChon.setTenKM(tenKM);
            khuyenMaiChon.setMaSP(maSP);
            khuyenMaiChon.setUuDai(uuDai);
            khuyenMaiChon.setNgayBD(ngayBD);
            khuyenMaiChon.setNgayKT(ngayKT);

            xuLyThoat();
        } catch (NumberFormatException | ParseException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu khuyến mãi không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void xuLyThoat() {
        // Tìm JDialog chứa panel này và đóng nó
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JDialog) {
            JDialog dialog = (JDialog) window;
            dialog.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Mã SP", "Ưu đãi", "Ngày bắt đầu", "Ngày kết thúc", "Tình trạng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Chọn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        xuLyChonKhuyenMai();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        xuLyThoat();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
